apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-api
  labels:
    tier: "backend"
    release: "stable"
    environment: "production"
    app.kubernetes.io/name: teacher-api
    app.kubernetes.io/version: "2.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: "backend"
      release: "stable"
      environment: "production"
      app.kubernetes.io/name: teacher-api
      app.kubernetes.io/version: "2.0"
  template:
    metadata:
      labels:
        tier: "backend"
        release: "stable"
        environment: "production"
        app.kubernetes.io/name: teacher-api
        app.kubernetes.io/version: "2.0"
    spec:
      containers:
        - image: campusnaa/teacherapi:latest
          name: teacher
          imagePullPolicy: Always
          ports:
            - name: api-port
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: teacher-config
            - secretRef:
                name: teacher-secret
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      priorityClassName: high-priority
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: teacher-service
spec:
  selector:
    tier: "backend"
    release: "stable"
    environment: "production"
    app.kubernetes.io/name: teacher-api
    app.kubernetes.io/version: "2.0"
  ports:
    - name: http
      port: 80
      targetPort: api-port
    - name: https
      port: 443
      targetPort: api-port
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: teacher-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teacher-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: teacher-api-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: teacher-api
  updatePolicy:
    updateMode: "Auto"
