apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::240391254719:role/EKSNodeGroupRole
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: "- groups: \n  - system:masters\n  userarn: arn:aws:iam::240391254719:root\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-06-14T13:34:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "18489"
  uid: 0c9f60a7-a7ce-4743-95d6-daf53c051c90
