apiVersion: v1
kind: Pod
metadata:
  name: s3-cp-pod
spec:
  containers:
    - name: s3-cp-container
      image: amazon/aws-cli
      command: ["/bin/sh", "-c"]
      args:
        - |
          aws s3 cp s3://your-s3-bucket/path/to/data /path/in/pod
      volumeMounts:
        - name: s3-volume
          mountPath: /path/in/pod
  volumes:
    - name: s3-volume
      secret:
        secretName: aws-credentials
