apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  MONGODB_REPLICA_SET_NAME: "rs0"
  MONGODB_PORT_NUMBER: "27017"
  MONGODB_INITIAL_PRIMARY_HOST: "mongodb"
  MONGODB_INITIAL_PRIMARY_PORT_NUMBER: "27017"
  MONGODB_ADVERTISED_HOSTNAME: "mongodb"
  MONGODB_ENABLE_JOURNAL: "true"
