apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-data
  namespace: moodle-elife
  labels:
    app: moodle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
