# my-helm-chart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
type: Opaque
data:
  MYSQL_PASSWORD: {{ .Values.secret.mysqlPassword | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.awsSecretAccessKey | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secret.awsAccessKeyId | b64enc | quote }}
  MYSQL_USER: {{ .Values.secret.mysqlUser | b64enc | quote }}
  MYSQL_HOST: {{ .Values.secret.mysqlHost | b64enc | quote }}
  AWS_MASTER_ACCOUNT_ID: {{ .Values.secret.awsMasterAccountId | b64enc | quote }}
