# my-helm-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
        {{- toYaml .Values.labels | nindent 4 }}
spec:
  selector:
      {{- toYaml .Values.labelsSelector | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: api-port
    - name: https
      port: 443
      targetPort: api-port
  type: {{ .Values.service.type }}
